---
before_install:
  - gem update --system
  - gem update bundler
language: ruby
rvm:
  - ruby-head
env:
  global:
    NOBENCHMARK=1
script:
  - ruby -rracc -e 'p Racc::VERSION'
  - patch -p1 -d /home/travis/.rvm/gems/ruby-head/gems/racc-1.4.14 < debug.patch
  - rake
